### ISSUE TITLE
Future roadmap

### ISSUE THREAD

**Issue by davidjbradshaw** [davidjbradshaw/iframe-resizer#1255]
### Features
 
- [ ]  log when new element is used to calculate size
- [ ] Add Parent option to create `data-iframe-size` attrs via CSS selector
- [ ] When `checkOrigin` has more than one target, iterate over them with `postMessage()`, rather than use `*`
    - #707
- [ ] Migrate `warning` to `tiny-warning` in React version
- [ ] Detect and ignore elements elements anchored to the page bottom/right of the page
- [ ] Detect when an iframe is removed from the page and auto disconnect with warning message
- [ ] Add `scrollBy()` method
- [ ] Add object `{ top: left: behaviour: }` to scrollTo / scrollToOffeset
- [ ] Add `getTopInfo()` method
- [ ] Migrate to using pubSub patten
- [ ] Add `EventListener()` methods
    - #710 
- [ ] Investigate scrolling with sticky headers
    - #794
- [ ] Add auto same-domain code injection (@iframe-resizer/injector))
 
### Framework components / plugins roadmap

 - [ ] Vue 3 / Nuxt
 - [ ] Svelte
 - [ ] SolidJS

**Comment by b2storefront** [comment]
out of curiosity did anyone tried to use that great product to fetch a Shopify page through iframe?

**Comment by seregacode** [comment]
I'm 2^8 subscriber !!!

**Comment by bertho-zero** [comment]
A request–response system would be great too, similar to sendMessage/onMessage but where you wait for a response.
For example somewhere in the parent we would do an `const data = await iFrame.request('fn', 'anArg')`

**Comment by davidjbradshaw** [comment]
@bertho-zero I got half way to that in a Stack Overflow answer a while back.

https://stackoverflow.com/questions/78565340/iframe-postmessage-alternatives-existing-eg-bind-functions-to-iframe/

**Comment by bertho-zero** [comment]
I was thinking of something like this that allows replying asynchronously and using async/await. I’m using something similar, but a native system to call parent <-> child functions and wait for the responses could help.

It’s just about making better use of the current messaging system for asynchronous behavior; the limitations related to data formatting remain the same.

**Child:**
```js
async function handleRequest({ action, payload }) {
  switch (action) {
    case 'anOperation':
      return { aKey: 'value' };
    default:
      throw new Error('Unknown action: ' + action);
  }
}

function onMessage(message) {
  if (message?.type === 'request') {
    handleRequest(message)
      .then(
        (result) => {
          if ('parentIFrame' in window) {
            window.parentIFrame.sendMessage({
              type: 'response',
              id: message.id,
              result,
            });
          }
        },
        (err) => {
          if ('parentIFrame' in window) {
            window.parentIFrame.sendMessage({
              type: 'response',
              id: message.id,
              error: String(err),
            });
          }
        },
      );
  }
};
```

**Parent**
```js
// on each iframe

const pendingRequests = new Map();
iframe.iFrameResizer.pendingRequests = pendingRequests;
iframe.iFrameResizer.callChild = function callChild(action, payload = {}) {
  return new Promise((resolve, reject) => {
    const id = crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);

    pendingRequests.set(id, { resolve, reject });
    iframe.iFrameResizer.sendMessage({ type: 'request', id, action, payload });
  });
};;


// in the `onMessage` function

const { pendingRequests } = iframe.iFrameResizer;

if (message.type === 'response' && pendingRequests?.has(message.id)) {
  const { resolve, reject } = pendingRequests.get(message.id);
  pendingRequests.delete(message.id);
  if (message.error) {
    reject(message.error);
  } else {
    resolve(message.result);
  }
}


// call example:

const result = await iframe.iFrameResizer.callChild('anOperation', {
  uid: 123456,
});
```

Here’s the ChatGPT conversation that inspired me, it works perfectly.

---

You:

With iframe-resizer, how can I call an asynchronous function and wait for its response?

ChatGPT:

Thought for 29 seconds

Here’s a **request/response pattern with Promises** for *iframe-resizer*. The idea: tag each request with an `id`, listen to `onMessage`, and resolve the Promise when the matching response returns.

### Parent side (page that contains the `<iframe>`)

```html
<script src="iframeResizer.min.js"></script>
<iframe id="child" src="..."></iframe>
<script>
  const iframe = document.getElementById('child');
  const pending = new Map();

  // Init + listen for messages from the child
  iFrameResize({
    checkOrigin: true,
    onMessage({ iframe, message }) {
      if (message?.type === 'response' && pending.has(message.id)) {
        const { resolve } = pending.get(message.id);
        pending.delete(message.id);
        resolve(message.result);
      }
    }
  }, iframe);

  // Call the child and wait for the response
  function callChild(action, payload, { timeout = 8000, targetOrigin = '*' } = {}) {
    return new Promise((resolve, reject) => {
      const id = crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
      const timer = setTimeout(() => {
        pending.delete(id);
        reject(new Error('Timeout'));
      }, timeout);

      pending.set(id, { resolve, reject, timer });
      iframe.iFrameResizer.sendMessage({ type: 'request', id, action, payload }, targetOrigin);
    });
  }

  // Example usage
  // const data = await callChild('computeTotal', { items: [1,2,3] });
</script>
```

*API refs: `onMessage` (parent) and `sendMessage` on the parent side.* [iframe-resizer](https://iframe-resizer.com/api/parent/)

### Iframe side (embedded page)

```html
<script src="iframeResizer.contentWindow.min.js"></script>
<script>
  // Declare the message handler in the iframe via window.iFrameResizer
  window.iFrameResizer = {
    // The parent will send {type:'request', id, action, payload}
    onMessage(message) {
      if (message?.type === 'request') {
        handleRequest(message).catch(err => {
          parentIframe.sendMessage({ type: 'response', id: message.id, error: String(err) });
        });
      }
    },
    onReady() {
      // here if needed: parentIframe.sendMessage({ type:'ready' })
    }
  };

  async function handleRequest({ id, action, payload }) {
    let result;
    switch (action) {
      case 'computeTotal':
        result = await computeTotal(payload);
        break;
      // other actions...
      default:
        throw new Error('Unknown action: ' + action);
    }
    parentIframe.sendMessage({ type: 'response', id, result });
  }

  async function computeTotal({ items }) {
    await new Promise(r => setTimeout(r, 200)); // simulate async
    return items.reduce((a, b) => a + b, 0);
  }
</script>
```

*API refs: `onMessage` (child via `window.iFrameResizer`) and `parentIframe.sendMessage`.* [iframe-resizer](https://iframe-resizer.com/api/child/)

---

#### Key points

-   **No native `await`** on `sendMessage`: you roll your own Promise with a correlation `id` and `onMessage`. [iframe-resizer+1](https://iframe-resizer.com/api/parent/)
    
-   **Security**: set `checkOrigin: true` on the parent and, on the iframe side, use the `targetOrigin` option when possible. [iframe-resizer+1](https://iframe-resizer.com/api/parent/)
    
-   **Initialization**: wait for the iframe to be initialized (`onReady` in the iframe) before sending heavy requests. [iframe-resizer](https://iframe-resizer.com/api/child/)
    

If you want the reverse (the iframe calls a function in the parent and waits), apply the same pattern: a `pending` map in the iframe, `parentIframe.sendMessage({...})`, and `onMessage` in the parent that sends a response with the same `id`.

**Comment by davidjbradshaw** [comment]
That's pretty dam impressive, I've had the idea of creating this type of thing as an add-on package for a while, rather than rolling it into the main thing. I think it is a bit two niche and complex to add to the main packages, as I want to keep the API surface as simple as I can.

**Comment by nynevi** [comment]
@bertho-zero see:
- https://github.com/krakenjs/post-robot
- https://github.com/krakenjs/zoid
